### ISSUE TITLE
Add some debug logging

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/sentinel-forward-data-action#9]
While working with the action I realized it might be nice to confirm that the action is sending the correct data, might be nice to log the filename and size here: https://github.com/cds-snc/sentinel-forward-data-action/blob/main/src/lib/forwarder.py#L50

**Comment by sylviamclaughlin** [comment]
Added additional logging in this [PR](https://github.com/cds-snc/sentinel-forward-data-action/pull/13/files).
